# docker-compose.yml
version: "3.9"
services:
  web:
    container_name: web
    build: .
    # TODO remove hard code sleep, it should use short sleep retry in entrypoint.sh
    command: bash -c "sleep 15 && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code # mount current folder to /code folder in side a container
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - compose_network
  db:
    container_name: mysql-server
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    ports:
      - 3306:3306
    volumes:
      # Use name volumes, managed by Docker for local development
      - mysql-data:/var/lib/mysql
      - mysql-logs:/var/log/mysql
    networks:
      - compose_network
# https://docs.docker.com/compose/compose-file/compose-file-v3/#external-1
volumes:
  mysql-data:
  mysql-logs:
# https://serverfault.com/questions/871090/how-to-use-docker-secrets-without-a-swarm-cluster
networks:
  compose_network:
