# Generated by Django 4.1.1 on 2022-09-28 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='created_at',
            new_name='date_at',
        ),
    ]
