# Generated by Django 4.1.1 on 2022-09-28 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_rename_created_at_loan_date_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='date_at',
            new_name='created_at',
        ),
    ]
